### ISSUE TITLE
No in kernel USB

### ISSUE THREAD

**Issue by bjdooks-ct** [polarfire-soc/meta-polarfire-soc-yocto-bsp#11]
The usb device works under HSS as you can use it to download images to the eMMC.
Although there is a device tree node for the mssusb, there is no current in kernel support

**Comment by lewishanly** [comment]
MUSB Driver developed and under test, will be available for the next release planned late December.

**Comment by bjdooks-ct** [comment]
Hi, verified it can see devices when in host mode but have not done any extensive testing.
