### ISSUE TITLE
eMMC only using 4-bit bus

### ISSUE THREAD

**Issue by bjdooks-ct** [polarfire-soc/meta-polarfire-soc-yocto-bsp#12]
The eMMC is connected by an 8-bit bus but the kernel is only configured for 4-bit.
This is causing half the performance of eMMC (11.46MB/sec) than the 8-bit config

**Comment by lewishanly** [comment]
The design supports 8, will test for the release late December.

**Comment by bjdooks-ct** [comment]
This looks like it has been added in the 2021.02 release.

**Comment by lhanlyu** [comment]
Shared DT entry, so once again is the lowest 4.
