### ISSUE TITLE
populate_sdk fails

### ISSUE THREAD

**Issue by davidhuwyler** [polarfire-soc/meta-polarfire-soc-yocto-bsp#13]
bitbake <image> populate_sdk 
-- or --
bitbake meta-toolchain 

both fail.
Any chance they will work in the future?

**Comment by eppidei** [comment]
Hello,
here is a video that explains how to build sdk.
https://www.youtube.com/watch?v=X1Z4PgGo4J8&list=PL9B4edd-p2aiesb5K9TKQpoyGJlPAmq8x&index=4
It has been tested with previous tag but it should work also with the last one.

**Comment by davidhuwyler** [comment]
Ok this worked for me thanks! --> closed
