### ISSUE TITLE
Query: Kernel upgrade from 5.6

### ISSUE THREAD

**Issue by pathakraul** [polarfire-soc/meta-polarfire-soc-yocto-bsp#26]
Hi,

The current kernel supported is 5.6. Will there be a kernel upgrade, probably 5.12?
If there is, any idea when it will happen?

Thanks
Rahul

**Comment by lhanlyu** [comment]
Yes this is planned and should be tested and released in the next couple of weeks.

**Comment by pathakraul** [comment]
Thanks for letting me know. 
I wanted to try something so I upgraded the kernel to 5.12, except the patches for uDMA and RTC.

Will wait for the official release

**Comment by lhanlyu** [comment]
Latest release has kernel 5.12.1
