### ISSUE TITLE
List of Known Good NVMes?

### ISSUE THREAD

**Issue by BlamKiwi** [polarfire-soc/meta-polarfire-soc-yocto-bsp#40]
I'm aware of the existing issues with using NVMe drives on the Icicle Dev Kit. Is there a list of known good NVMe drives that will work?

**Comment by mcnamarad1971** [comment]
Hi, the upcoming release has been specifically targeted to resolve NVMe issues.  Its been tested extensively with a wide variety of commonly available NVMe drives.  I suggest you watch the repo and upgrade the design and yocto recipes and check if your NVMe issues are resolved. Its scheduled to be published in the next week or so.

**Comment by lhanlyu** [comment]
All NVME PCIe issues are resolved, should you find any issues please let us know.
