### ISSUE TITLE
riscv-yocto.xml not found in main branch or 2023 branch.

### ISSUE THREAD

**Issue by Jpgig** [polarfire-soc/meta-polarfire-soc-yocto-bsp#47]
Earlier branches have riscv-yocto.xml file, but main branch or none of the 2023 branch contains this file.
Can anyone help with this?
https://github.com/polarfire-soc/meta-polarfire-soc-yocto-bsp/issues

**Comment by lhanlyu** [comment]
The repository used for the manifest (xml) file changed in the 2023 release.

Please see the Readme in the following repository:
https://github.com/polarfire-soc/polarfire-soc-yocto-manifests
