### ISSUE TITLE
 Kernel panic - not syncing: Attempted to kill the idle task!

### ISSUE THREAD

**Issue by Jpgig** [polarfire-soc/meta-polarfire-soc-yocto-bsp#48]
While running polarfore-soc-yocto-bsp 2021.11 version from the below link:
https://github.com/polarfire-soc/meta-polarfire-soc-yocto-bsp/tree/2021.11

I'm getting Kernel panic error as shown in below screen shot.
![image](https://user-images.githubusercontent.com/115164852/230142109-c6829352-c35d-4967-ac9b-04e4053bda75.png)

Appreciate help to resolve this.

**Comment by lhanlyu** [comment]
This issue was fixed in later releases. can you try the latest release.

**Comment by Jpgig** [comment]
I want to integrate ROS Honister release so need to use this branch - Honister. Can you suggest the modification?

**Comment by lhanlyu** [comment]
Can you provide more logs? Later releases also use Honister?

**Comment by Jpgig** [comment]
Below are more details about the log:
![image](https://user-images.githubusercontent.com/115164852/230901437-d7648bd9-7813-435d-846a-68df364f12da.png)

![image](https://user-images.githubusercontent.com/115164852/230901484-3db8afdc-8be5-44a6-9d69-64f0aa6c1313.png)

Also, where can I find the mapping of the reference design to the Polarfire yocto build version? I am using Polarfire soc yocto build the 2021.11 version.

**Comment by lhanlyu** [comment]
The icicle-kit reference design and yocto bsp releases are always on the same release date.
If using the 2021.11 yocto release, you should use  https://github.com/polarfire-soc/icicle-kit-reference-design/releases 2021.11

If at all possible you should try to update.
