### ISSUE TITLE
System only sees 1GiB DDR

### ISSUE THREAD

**Issue by bjdooks-ct** [polarfire-soc/meta-polarfire-soc-yocto-bsp#7]
The board has 2GiB of DDR but both u-boot and Linux are only seeing 1GiB of it.

**Comment by lewishanly** [comment]
Currently in development to resolve 64-bit address with yocto builds. Should be available early 2021.

**Comment by kelas** [comment]
+1

Also, some moving parts in HSS are hardcoded to 1GiB:

https://github.com/polarfire-soc/hart-software-services/issues/11#issue-791705156

**Comment by bjdooks-ct** [comment]
I assume the PCIe only having a 512MiB window is also related to this.

**Comment by bjdooks-ct** [comment]
The 2020.12 release of the HSS and yocto seem to have solved the memory issue.
