### ISSUE TITLE
CONFIG_VFAT is not set

### ISSUE THREAD

**Issue by bjdooks-ct** [polarfire-soc/meta-polarfire-soc-yocto-bsp#8]
The default u-boot/boot partition is vfat, so having vfat enabled would allow in-linux configuration of u-boot

**Comment by lewishanly** [comment]
Added in for the next release late December.

**Comment by ant9000** [comment]
The issue could be closed - solved as of release 2021.02

**Comment by Cyril-Jean** [comment]
Resolved in 2021.02 release.
